version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ./html:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ueex_tt
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "7776:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8181:80"
    depends_on:
      - db

volumes:
  db_data:
